package fr.fifou.economy.blocks.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelVault2by2 extends ModelBase
{
    ModelRenderer BASE;
    ModelRenderer WheelBar_3;
    ModelRenderer WheelBar_2;
    ModelRenderer WheelBar_2_Ball;
    ModelRenderer WheelBar_4_Thin;
    ModelRenderer WheelBar_3_Ball;
    ModelRenderer WheelBar_3_Thin;
    ModelRenderer WheelBar_4_Ball;
    ModelRenderer WheelBar_4;
    ModelRenderer WheelBar_1_Ball;
    ModelRenderer Wheel_1;
    ModelRenderer Panel_front;
    ModelRenderer Wheel_2;
    ModelRenderer WheelBar_1_Thin;
    ModelRenderer Wheel_3;
    ModelRenderer WheelBar_2_Thin;
    ModelRenderer Roof;
    ModelRenderer Panel_back;
    ModelRenderer Panel_right;
    ModelRenderer WheelBar_1;
    ModelRenderer Panel_left;
    ModelRenderer plank_support;
    ModelRenderer Bills_duplication;
    ModelRenderer Bills2;
    ModelRenderer Bills3;
    ModelRenderer Bills4;
    ModelRenderer Bills5;
    ModelRenderer Bills1;
    ModelRenderer Bills21;
    ModelRenderer Bills31;
    ModelRenderer Bills41;
    ModelRenderer Bills51;

    public ModelVault2by2()
    {
        this(0.0F);
    }

    public ModelVault2by2(float par1)
    {
        this.BASE = new ModelRenderer(this, 0, 3);
        this.BASE.setTextureSize(256, 128);
        this.BASE.addBox(-8.0F, -0.5F, -16.0F, 16, 1, 32);
        this.BASE.setRotationPoint(-8.0F, 23.5F, 0.0F);
        this.WheelBar_3 = new ModelRenderer(this, 46, 70);
        this.WheelBar_3.setTextureSize(256, 128);
        this.WheelBar_3.addBox(-1.0F, -1.0F, -3.0F, 2, 2, 6);
        this.WheelBar_3.setRotationPoint(-20.0F, 8.0F, 5.0F);
        this.WheelBar_2 = new ModelRenderer(this, 36, 70);
        this.WheelBar_2.setTextureSize(256, 128);
        this.WheelBar_2.addBox(-1.0F, -3.0F, -1.0F, 2, 6, 2);
        this.WheelBar_2.setRotationPoint(-20.0F, 13.0F, 0.0F);
        this.WheelBar_2_Ball = new ModelRenderer(this, 64, 74);
        this.WheelBar_2_Ball.setTextureSize(256, 128);
        this.WheelBar_2_Ball.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.WheelBar_2_Ball.setRotationPoint(-20.0F, 18.0F, 0.0F);
        this.WheelBar_4_Thin = new ModelRenderer(this, 66, 70);
        this.WheelBar_4_Thin.setTextureSize(256, 128);
        this.WheelBar_4_Thin.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
        this.WheelBar_4_Thin.setRotationPoint(-20.0F, 8.0F, -8.5F);
        this.WheelBar_3_Ball = new ModelRenderer(this, 64, 74);
        this.WheelBar_3_Ball.setTextureSize(256, 128);
        this.WheelBar_3_Ball.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.WheelBar_3_Ball.setRotationPoint(-20.0F, 8.0F, 10.0F);
        this.WheelBar_3_Thin = new ModelRenderer(this, 66, 70);
        this.WheelBar_3_Thin.setTextureSize(256, 128);
        this.WheelBar_3_Thin.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
        this.WheelBar_3_Thin.setRotationPoint(-20.0F, 8.0F, 8.5F);
        this.WheelBar_4_Ball = new ModelRenderer(this, 64, 74);
        this.WheelBar_4_Ball.setTextureSize(256, 128);
        this.WheelBar_4_Ball.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.WheelBar_4_Ball.setRotationPoint(-20.0F, 8.0F, -10.0F);
        this.WheelBar_4 = new ModelRenderer(this, 46, 70);
        this.WheelBar_4.setTextureSize(256, 128);
        this.WheelBar_4.addBox(-1.0F, -1.0F, -3.0F, 2, 2, 6);
        this.WheelBar_4.setRotationPoint(-20.0F, 8.0F, -5.0F);
        this.WheelBar_1_Ball = new ModelRenderer(this, 64, 74);
        this.WheelBar_1_Ball.setTextureSize(256, 128);
        this.WheelBar_1_Ball.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.WheelBar_1_Ball.setRotationPoint(-20.0F, -2.0F, 0.0F);
        this.Wheel_1 = new ModelRenderer(this, 13, 70);
        this.Wheel_1.setTextureSize(256, 128);
        this.Wheel_1.addBox(-1.0F, -2.0F, -2.0F, 2, 4, 4);
        this.Wheel_1.setRotationPoint(-16.0F, 8.0F, 0.0F);
        this.Panel_front = new ModelRenderer(this, 4, 68);
        this.Panel_front.setTextureSize(256, 128);
        this.Panel_front.addBox(-0.5F, -15.0F, -15.0F, 1, 30, 30);
        this.Panel_front.setRotationPoint(-14.5F, 8.0F, 0.0F);
        this.Wheel_2 = new ModelRenderer(this, 26, 74);
        this.Wheel_2.setTextureSize(256, 128);
        this.Wheel_2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.Wheel_2.setRotationPoint(-18.0F, 8.0F, 0.0F);
        this.WheelBar_1_Thin = new ModelRenderer(this, 66, 70);
        this.WheelBar_1_Thin.setTextureSize(256, 128);
        this.WheelBar_1_Thin.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
        this.WheelBar_1_Thin.setRotationPoint(-20.0F, -0.5F, 0.0F);
        this.Wheel_3 = new ModelRenderer(this, 13, 70);
        this.Wheel_3.setTextureSize(256, 128);
        this.Wheel_3.addBox(-1.0F, -2.0F, -2.0F, 2, 4, 4);
        this.Wheel_3.setRotationPoint(-20.0F, 8.0F, 0.0F);
        this.WheelBar_2_Thin = new ModelRenderer(this, 66, 70);
        this.WheelBar_2_Thin.setTextureSize(256, 128);
        this.WheelBar_2_Thin.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
        this.WheelBar_2_Thin.setRotationPoint(-20.0F, 16.5F, 0.0F);
        this.Roof = new ModelRenderer(this, 0, 3);
        this.Roof.setTextureSize(256, 128);
        this.Roof.addBox(-8.0F, -0.5F, -16.0F, 16, 1, 32);
        this.Roof.setRotationPoint(-8.0F, -7.5F, 0.0F);
        this.Panel_back = new ModelRenderer(this, 67, 49);
        this.Panel_back.setTextureSize(256, 128);
        this.Panel_back.addBox(-0.5F, -15.0F, -15.0F, 1, 30, 30);
        this.Panel_back.setRotationPoint(-0.5F, 8.0F, 0.0F);
        this.Panel_right = new ModelRenderer(this, 0, 37);
        this.Panel_right.setTextureSize(256, 128);
        this.Panel_right.addBox(-8.0F, -15.0F, -0.5F, 16, 30, 1);
        this.Panel_right.setRotationPoint(-8.0F, 8.0F, -15.5F);
        this.WheelBar_1 = new ModelRenderer(this, 36, 70);
        this.WheelBar_1.setTextureSize(256, 128);
        this.WheelBar_1.addBox(-1.0F, -3.0F, -1.0F, 2, 6, 2);
        this.WheelBar_1.setRotationPoint(-20.0F, 3.0F, 0.0F);
        this.Panel_left = new ModelRenderer(this, 0, 37);
        this.Panel_left.setTextureSize(256, 128);
        this.Panel_left.addBox(-8.0F, -15.0F, -0.5F, 16, 30, 1);
        this.Panel_left.setRotationPoint(-8.0F, 8.0F, 15.5F);
        this.plank_support = new ModelRenderer(this, 100, 98);
        this.plank_support.setTextureSize(256, 128);
        this.plank_support.addBox(-7.0F, -0.5F, -14.5F, 14, 1, 29);
        this.plank_support.setRotationPoint(-7.5F, 8.0F, 0.0F);
        this.Bills_duplication = new ModelRenderer(this, 68, 113);
        this.Bills_duplication.setTextureSize(256, 128);
        this.Bills_duplication.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills_duplication.setRotationPoint(-8.0F, 21.0F, 11.0F);
        this.Bills2 = new ModelRenderer(this, 68, 113);
        this.Bills2.setTextureSize(256, 128);
        this.Bills2.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills2.setRotationPoint(-8.0F, 17.0F, 11.0F);
        this.Bills3 = new ModelRenderer(this, 97, 22);
        this.Bills3.setTextureSize(256, 128);
        this.Bills3.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills3.setRotationPoint(-8.0F, 21.0F, -11.0F);
        this.Bills4 = new ModelRenderer(this, 100, 40);
        this.Bills4.setTextureSize(256, 128);
        this.Bills4.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills4.setRotationPoint(-8.0F, 21.0F, 1.0F);
        this.Bills5 = new ModelRenderer(this, 100, 53);
        this.Bills5.setTextureSize(256, 128);
        this.Bills5.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills5.setRotationPoint(-7.0F, 17.0F, -11.0F);
        this.Bills1 = new ModelRenderer(this, 68, 113);
        this.Bills1.setTextureSize(256, 128);
        this.Bills1.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills1.setRotationPoint(-8.0F, 5.5F, 11.0F);
        this.Bills21 = new ModelRenderer(this, 100, 66);
        this.Bills21.setTextureSize(256, 128);
        this.Bills21.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills21.setRotationPoint(-7.0F, 1.5F, 11.0F);
        this.Bills31 = new ModelRenderer(this, 100, 53);
        this.Bills31.setTextureSize(256, 128);
        this.Bills31.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills31.setRotationPoint(-8.0F, 5.5F, -11.0F);
        this.Bills41 = new ModelRenderer(this, 97, 22);
        this.Bills41.setTextureSize(256, 128);
        this.Bills41.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills41.setRotationPoint(-7.0F, 5.5F, 1.0F);
        this.Bills51 = new ModelRenderer(this, 100, 40);
        this.Bills51.setTextureSize(256, 128);
        this.Bills51.addBox(-6.0F, -2.0F, -4.0F, 12, 4, 8);
        this.Bills51.setRotationPoint(-7.0F, 1.5F, -11.0F);
    }

    public void renderAll()
    {
        float f = 0.0625F;
        this.BASE.rotateAngleX = 0.0F;
        this.BASE.rotateAngleY = 0.0F;
        this.BASE.rotateAngleZ = 0.0F;
        this.BASE.renderWithRotation(f);
        this.WheelBar_3.rotateAngleX = 0.0F;
        this.WheelBar_3.rotateAngleY = 0.0F;
        this.WheelBar_3.rotateAngleZ = 0.0F;
        this.WheelBar_3.renderWithRotation(f);
        this.WheelBar_2.rotateAngleX = 0.0F;
        this.WheelBar_2.rotateAngleY = 0.0F;
        this.WheelBar_2.rotateAngleZ = 0.0F;
        this.WheelBar_2.renderWithRotation(f);
        this.WheelBar_2_Ball.rotateAngleX = 0.0F;
        this.WheelBar_2_Ball.rotateAngleY = 0.0F;
        this.WheelBar_2_Ball.rotateAngleZ = 0.0F;
        this.WheelBar_2_Ball.renderWithRotation(f);
        this.WheelBar_4_Thin.rotateAngleX = 0.0F;
        this.WheelBar_4_Thin.rotateAngleY = 0.0F;
        this.WheelBar_4_Thin.rotateAngleZ = 0.0F;
        this.WheelBar_4_Thin.renderWithRotation(f);
        this.WheelBar_3_Ball.rotateAngleX = 0.0F;
        this.WheelBar_3_Ball.rotateAngleY = 0.0F;
        this.WheelBar_3_Ball.rotateAngleZ = 0.0F;
        this.WheelBar_3_Ball.renderWithRotation(f);
        this.WheelBar_3_Thin.rotateAngleX = 0.0F;
        this.WheelBar_3_Thin.rotateAngleY = 0.0F;
        this.WheelBar_3_Thin.rotateAngleZ = 0.0F;
        this.WheelBar_3_Thin.renderWithRotation(f);
        this.WheelBar_4_Ball.rotateAngleX = 0.0F;
        this.WheelBar_4_Ball.rotateAngleY = 0.0F;
        this.WheelBar_4_Ball.rotateAngleZ = 0.0F;
        this.WheelBar_4_Ball.renderWithRotation(f);
        this.WheelBar_4.rotateAngleX = 0.0F;
        this.WheelBar_4.rotateAngleY = 0.0F;
        this.WheelBar_4.rotateAngleZ = 0.0F;
        this.WheelBar_4.renderWithRotation(f);
        this.WheelBar_1_Ball.rotateAngleX = 0.0F;
        this.WheelBar_1_Ball.rotateAngleY = 0.0F;
        this.WheelBar_1_Ball.rotateAngleZ = 0.0F;
        this.WheelBar_1_Ball.renderWithRotation(f);
        this.Wheel_1.rotateAngleX = 0.0F;
        this.Wheel_1.rotateAngleY = 0.0F;
        this.Wheel_1.rotateAngleZ = 0.0F;
        this.Wheel_1.renderWithRotation(f);
        this.Panel_front.rotateAngleX = 0.0F;
        this.Panel_front.rotateAngleY = 0.0F;
        this.Panel_front.rotateAngleZ = 0.0F;
        this.Panel_front.renderWithRotation(f);
        this.Wheel_2.rotateAngleX = 0.0F;
        this.Wheel_2.rotateAngleY = 0.0F;
        this.Wheel_2.rotateAngleZ = 0.0F;
        this.Wheel_2.renderWithRotation(f);
        this.WheelBar_1_Thin.rotateAngleX = 0.0F;
        this.WheelBar_1_Thin.rotateAngleY = 0.0F;
        this.WheelBar_1_Thin.rotateAngleZ = 0.0F;
        this.WheelBar_1_Thin.renderWithRotation(f);
        this.Wheel_3.rotateAngleX = 0.0F;
        this.Wheel_3.rotateAngleY = 0.0F;
        this.Wheel_3.rotateAngleZ = 0.0F;
        this.Wheel_3.renderWithRotation(f);
        this.WheelBar_2_Thin.rotateAngleX = 0.0F;
        this.WheelBar_2_Thin.rotateAngleY = 0.0F;
        this.WheelBar_2_Thin.rotateAngleZ = 0.0F;
        this.WheelBar_2_Thin.renderWithRotation(f);
        this.Roof.rotateAngleX = 0.0F;
        this.Roof.rotateAngleY = 0.0F;
        this.Roof.rotateAngleZ = 0.0F;
        this.Roof.renderWithRotation(f);
        this.Panel_back.rotateAngleX = 0.0F;
        this.Panel_back.rotateAngleY = 0.0F;
        this.Panel_back.rotateAngleZ = 0.0F;
        this.Panel_back.renderWithRotation(f);
        this.Panel_right.rotateAngleX = 0.0F;
        this.Panel_right.rotateAngleY = 0.0F;
        this.Panel_right.rotateAngleZ = 0.0F;
        this.Panel_right.renderWithRotation(f);
        this.WheelBar_1.rotateAngleX = 0.0F;
        this.WheelBar_1.rotateAngleY = 0.0F;
        this.WheelBar_1.rotateAngleZ = 0.0F;
        this.WheelBar_1.renderWithRotation(f);
        this.Panel_left.rotateAngleX = 0.0F;
        this.Panel_left.rotateAngleY = 0.0F;
        this.Panel_left.rotateAngleZ = 0.0F;
        this.Panel_left.renderWithRotation(f);
        this.plank_support.rotateAngleX = 0.0F;
        this.plank_support.rotateAngleY = 0.0F;
        this.plank_support.rotateAngleZ = 0.0F;
        this.plank_support.renderWithRotation(f);
        this.Bills_duplication.rotateAngleX = 0.0F;
        this.Bills_duplication.rotateAngleY = 0.0F;
        this.Bills_duplication.rotateAngleZ = 0.0F;
        this.Bills_duplication.renderWithRotation(f);
        this.Bills2.rotateAngleX = 0.0F;
        this.Bills2.rotateAngleY = 0.0F;
        this.Bills2.rotateAngleZ = 0.0F;
        this.Bills2.renderWithRotation(f);
        this.Bills3.rotateAngleX = 0.0F;
        this.Bills3.rotateAngleY = 0.0F;
        this.Bills3.rotateAngleZ = 0.0F;
        this.Bills3.renderWithRotation(f);
        this.Bills4.rotateAngleX = 0.0F;
        this.Bills4.rotateAngleY = 0.0F;
        this.Bills4.rotateAngleZ = 0.0F;
        this.Bills4.renderWithRotation(f);
        this.Bills5.rotateAngleX = 0.0F;
        this.Bills5.rotateAngleY = 0.0F;
        this.Bills5.rotateAngleZ = 0.0F;
        this.Bills5.renderWithRotation(f);
        this.Bills1.rotateAngleX = 0.0F;
        this.Bills1.rotateAngleY = 0.0F;
        this.Bills1.rotateAngleZ = 0.0F;
        this.Bills1.renderWithRotation(f);
        this.Bills21.rotateAngleX = 0.0F;
        this.Bills21.rotateAngleY = 0.0F;
        this.Bills21.rotateAngleZ = 0.0F;
        this.Bills21.renderWithRotation(f);
        this.Bills31.rotateAngleX = 0.0F;
        this.Bills31.rotateAngleY = 0.0F;
        this.Bills31.rotateAngleZ = 0.0F;
        this.Bills31.renderWithRotation(f);
        this.Bills41.rotateAngleX = 0.0F;
        this.Bills41.rotateAngleY = 0.0F;
        this.Bills41.rotateAngleZ = 0.0F;
        this.Bills41.renderWithRotation(f);
        this.Bills51.rotateAngleX = 0.0F;
        this.Bills51.rotateAngleY = 0.0F;
        this.Bills51.rotateAngleZ = 0.0F;
        this.Bills51.renderWithRotation(f);
    }
}
